name: "Build and Publish Storybook to GitHub Pages"

on:
  push:
    branches:
      - docs-deploy

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: "Deploy Storybook to GitHub Pages"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: yarn install # default: npm ci
          build_command: yarn build-storybook # default: npm run build-storybook
          path: storybook-static # default: dist/storybook
          checkout: false # default: true
